# Generated by Django 3.2.9 on 2022-10-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20220731_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
