# Generated by Django 3.2.9 on 2022-08-04 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TastingNoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('star_rating', models.IntegerField()),
                ('one_line_review', models.CharField(max_length=50)),
                ('taste', models.CharField(max_length=20)),
                ('taste_intensity', models.IntegerField()),
                ('flavor', models.CharField(max_length=20)),
                ('flavor_intensity', models.IntegerField()),
                ('alchol_finish', models.IntegerField()),
                ('long_review', models.CharField(blank=True, max_length=300, null=True)),
                ('etc', models.CharField(blank=True, max_length=50, null=True)),
                ('etc_intensity', models.CharField(blank=True, max_length=50, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('UploadImagekey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UploadImageModel', to='showcase.uploadimagemodel')),
            ],
        ),
    ]
