# Generated by Django 3.2.9 on 2022-08-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tastingnotemodel',
            old_name='star_rating',
            new_name='drumtong_rating',
        ),
    ]
