# Generated by Django 3.2.9 on 2022-05-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagemodel',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='uploadimagemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
