# Generated by Django 3.2.9 on 2022-05-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20220503_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimagemodel',
            name='file',
        ),
    ]
