# Generated by Django 3.2.9 on 2022-05-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_remove_uploadimagemodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagemodel',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
