# Generated by Django 3.2.9 on 2022-05-08 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_alter_uploadimagemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimagemodel',
            name='nickname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
