# Generated by Django 3.2.9 on 2022-09-08 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_alter_tastingnotemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimagemodel',
            name='whiskyname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saveuser', models.CharField(blank=True, max_length=50, null=True)),
                ('savemodelkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.tastingnotemodel')),
            ],
        ),
    ]
