# Generated by Django 3.2.9 on 2022-05-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_uploadimagemodel_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagemodel',
            name='nickname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
