# Generated by Django 3.2.9 on 2022-09-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_auto_20220908_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='tastingnotemodel',
            name='followuser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadimagemodel',
            name='followuser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='SaveModel',
        ),
    ]
