# Generated by Django 3.2.9 on 2022-09-12 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_auto_20220912_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadnotefollowmodel',
            old_name='UploadImagekey',
            new_name='UploadNotekey',
        ),
        migrations.RemoveField(
            model_name='tastingnotemodel',
            name='followuser',
        ),
        migrations.AlterField(
            model_name='uploadimagefollowmodel',
            name='UploadImagekey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='showcase.uploadimagemodel'),
        ),
    ]
