# Generated by Django 3.2.9 on 2022-09-12 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_auto_20220912_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagefollowmodel',
            name='UploadImagekey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.uploadimagemodel'),
        ),
    ]
