# Generated by Django 3.2.9 on 2022-09-12 09:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0009_alter_uploadimagefollowmodel_uploadimagekey'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadImageFollowModel',
            new_name='ImageFollowModel',
        ),
        migrations.RenameModel(
            old_name='UploadNoteFollowModel',
            new_name='NoteFollowModel',
        ),
    ]
