# Generated by Django 3.2.9 on 2022-09-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0011_auto_20220913_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefollowmodel',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
