# Generated by Django 3.2.9 on 2022-05-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_remove_uploadimagemodel_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimagemodel',
            name='nickname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
