# Generated by Django 3.2.9 on 2022-09-25 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0013_commentcommentlikemodel_commentcommentmodel_commentlikemodel_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentcommentmodel',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
