# Generated by Django 3.2.9 on 2022-10-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0014_auto_20220925_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
