# Generated by Django 3.2.9 on 2022-10-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0015_alter_uploadimagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tastingnotemodel',
            name='one_line_review',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadimagemodel',
            name='whiskyname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
