# Generated by Django 3.2.9 on 2022-10-07 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0017_alter_tastingnotemodel_long_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='qnaquestionmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('question', models.CharField(max_length=1000)),
                ('questioner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='qnaanswermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('qnaquestionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.qnaquestionmodel')),
            ],
        ),
    ]
