# Generated by Django 3.2.9 on 2022-10-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0018_qnaanswermodel_qnaquestionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnaquestionmodel',
            name='question_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
