# Generated by Django 3.2.9 on 2022-10-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0019_qnaquestionmodel_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tastingnotemodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
